name: deploy

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      # version:
      #   description: 'Name of version (ie 5.5.0)'
      #   required: true

jobs:
  prebuild-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup nodejs
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - run: wget -nv "https://github.com/apple/foundationdb/releases/download/7.2.5/foundationdb-clients_7.2.5-1_amd64.deb"
    - run: sudo dpkg -i foundationdb-clients_7.2.5-1_amd64.deb
    - run: sudo mkdir -p /var/lib/foundationdb/data
    - run: wget -nv "https://github.com/apple/foundationdb/releases/download/7.2.5/foundationdb-server_7.2.5-1_amd64.deb"
    - run: sudo dpkg -i foundationdb-server_7.2.5-1_amd64.deb

    - run: npm ci
    - run: npm run prebuild
    - run: npm test

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: linux-x64
        path: prebuilds/linux-*
        retention-days: 5

  prebuild-macos:
    runs-on: macos-latest

    env:
      DYLD_LIBRARY_PATH: /usr/local/lib

    steps:
    - uses: actions/checkout@v4
    - name: Setup nodejs
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - run: wget -nv "https://github.com/apple/foundationdb/releases/download/7.2.5/FoundationDB-7.2.5_arm64.pkg"
    - run: sudo installer -pkg FoundationDB-7.2.5_arm64.pkg -target /

    - run: npm ci
    - run: npm test

    - run: npm run prebuild -- --arch=arm64

    - run: wget -nv "https://github.com/apple/foundationdb/releases/download/7.2.5/FoundationDB-7.2.5_x86_64.pkg"
    - run: sudo installer -pkg FoundationDB-7.2.5_x86_64.pkg -target /

    - run: npm run prebuild -- --arch=x64

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: darwin
        path: prebuilds/darwin-*
        retention-days: 5
        if-no-files-found: error

  # Disabled until the windows install image is fixed.
  # prebuild-windows:
  #   runs-on: windows-latest
  #   env:
  #     FOUNDATIONDB_INSTALL_PATH: "C:\\Program Files\\FoundationDB"

  #   steps:
  #   - uses: actions/checkout@v4
  #   - name: Setup nodejs
  #     uses: actions/setup-node@v4
  #     with:
  #       node-version: 22

  #   # Bleh - the 7.xx builds are currently missing one of the header files. More detail here:
  #   # https://forums.foundationdb.org/t/fdb-c-types-h-missing-in-windows-install-image/3817
  #   - run: (new-object net.webclient).DownloadFile('https://github.com/apple/foundationdb/releases/download/7.2.5/foundationdb-7.2.5-x64.msi', 'c:\foundationdb.msi')
  #   - run: dir c:\foundationdb.msi
  #   - run: msiexec /i c:\foundationdb.msi /quiet /passive /norestart /log install.log | Out-Null

  #   - run: echo "C:\\Program Files\\FoundationDB\bin" >> $GITHUB_PATH

  #   - run: npm ci
  #   - run: npm run prebuild

  #   # For some reason this test fails - it can't find the prebuild even though its *right there*!!
  #   # - run: npm test
  #   # - run: Get-ChildItem -Recurse prebuild

  #   - name: Upload artifacts
  #     uses: actions/upload-artifact@v4
  #     with:
  #       name: win32-x64
  #       path: prebuilds/win32-x64
  #       retention-days: 5

  deploy-npm:
    # needs: [prebuild-windows, prebuild-macos, prebuild-linux]
    needs: [prebuild-macos, prebuild-linux]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 22
        registry-url: 'https://registry.npmjs.org'

    - uses: actions/download-artifact@v4
      with:
        name: darwin
        path: prebuilds

    - uses: actions/download-artifact@v4
      with:
        name: linux-x64
        path: prebuilds

    - run: ls -R prebuilds

    # Ideally I shouldn't need this...
    - run: wget -nv "https://github.com/apple/foundationdb/releases/download/7.2.5/foundationdb-clients_7.2.5-1_amd64.deb"
    - run: sudo dpkg -i foundationdb-clients_7.2.5-1_amd64.deb

    # And I could just run the linux script last anyway.
    - run: npm ci
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
