name: test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20, 22, 24]

    steps:
    - uses: actions/checkout@v4
    - name: Setup Node ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - run: wget "https://github.com/apple/foundationdb/releases/download/7.3.63/foundationdb-clients_7.3.63-1_amd64.deb"
    - run: sudo dpkg -i foundationdb-clients_7.3.63-1_amd64.deb
    - run: sudo mkdir -p /var/lib/foundationdb/data
    - run: wget "https://github.com/apple/foundationdb/releases/download/7.3.63/foundationdb-server_7.3.63-1_amd64.deb"
    - run: sudo dpkg -i foundationdb-server_7.3.63-1_amd64.deb

    - run: npm ci
    - run: npm test
